(defun perm_back(a b c)
  (list b c a))
(defun perm_forw(a b c)
  (list c a b))
(defun symmetry(a b c)
  (list c b a))
(defun permute(func a b c)
  (funcall func a b c))
(write (list 1 2 3))
(fresh-line)
(write (permute #'symmetry 1 2 3))
(fresh-line)
