(defun sum (x y)
   (+ x y))
(defun pow (x k)
   (if (> k 0) 
      (* x (pow x (- k 1)))
      1))
(write (sum (sum (pow 2 2) 3) (sin 4)))
(fresh-line)
(write (sum (pow (cos 5) 2) (sum (pow 2 3) -1)))
(fresh-line)
(write (sum (sum (pow (read) 2) (pow (read) 3)) (sum  1 (* (read) 2))))
(fresh-line)
