name: C/C++ CI

on:
  push:
    branches: [ "parallel" ]
  pull_request:
    branches: [ "parallel" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: installation
      run: sudo apt install -y googletest libgtest-dev build-essential gcovr

    - name: run in lab2
      run: cd lab2

    - name: Compile main
      run: make

    - name: run main
      run: ./main

    - name: Compile unit tests with coverage
      run: make coverage

    - name: run unit tests
      run: ./main
      
    - name: Generate coverage report
      run: gcovr -r . --xml-pretty -o coverage.xml --gcov-ignore-parse-errors all

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}